name: pothole_impact_tracker
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.0.0 <4.0.0'

# Platform configuration
platforms:
  android: true

dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  sizer: ^2.0.15
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  sensors_plus: ^4.0.2
  sqflite: ^2.3.0
  workmanager: ^0.5.2
  web: any

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/