name: pothole_impact_tracker
description: Detection pothole impact tracker.
version: 1.1.6
environment: 
  sdk: '>=3.0.0 <4.0.0'

# Platform configuration
# platforms:
#   android: true

dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  sizer: ^2.0.15
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  sensors_plus: ^4.0.2
  sqflite: ^2.3.0
  workmanager: ^0.6.0
  web: any
  geolocator: ^13.0.4
  path_provider: ^2.1.2
  uuid: ^4.2.1
  http: ^1.2.1
  flutter_background_service: ^5.0.0
  flutter_background_service_android: ^6.3.0
  wakelock_plus: ^1.3.2

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/